apiVersion: v1
kind: Namespace
metadata:
  name: cf-web-namespace
  namespace: cf-web-namespace
---
apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIlkyWmxjbUpsY25adGQyRnlaVHBpYkdGamEyMWhiZz09IgoJCX0KCX0sCgkiSHR0cEhlYWRlcnMiOiB7CgkJIlVzZXItQWdlbnQiOiAiRG9ja2VyLUNsaWVudC8xOC4wNi4yLWNlIChsaW51eCkiCgl9Cn0=
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: cf-web-namespace
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
  name: cf-web-service
  namespace: cf-web-namespace
spec:
  type: LoadBalancer
  ports:
    - port: 30089
      targetPort: 80
  selector:
    app: cf-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cf-web-deployment
  namespace: cf-web-namespace
  labels:
    app: cf-web
spec:
  replicas: 10
  selector:
    matchLabels:
      app: cf-web
  template:
    metadata:
      labels:
        app: cf-web
    spec:
      containers:
      - name: cf-web
        image: docker.io/cferber/cf-web:blue
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: dockerhub-secret
